language: python

addons:
  apt:
    packages:
      - libenchant-dev

python:
  - "3.6"
  - "3.7-dev"

env:
  - DEPS="Django>=2.0,<2.1"

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install --dev $DEPS

script: py.test --cov
