language: python

python:
  - "3.6"
  - "3.7-dev"

env:
  - DEPS="Django>=2.0,<2.1"

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pip install -e .
  - pipenv run pip install $DEPS

script: pipenv run py.test --cov
